# Generated by Django 5.1 on 2024-09-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
        migrations.RenameModel(
            old_name="Sales",
            new_name="Sale",
        ),
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
