# Generated by Django 5.1 on 2024-09-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_products_product_rename_sales_sale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="null", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(default="None", max_length=150),
            preserve_default=False,
        ),
    ]
