# Generated by Django 5.1 on 2024-09-24 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_user_date_user_role_user_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
    ]
