# Generated by Django 4.2.16 on 2024-09-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_user_role"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="InventoryUser",
        ),
    ]
