# Generated by Django 4.2.16 on 2024-09-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_user_inventoryuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InventoryUser",
        ),
    ]
