# Generated by Django 5.1.1 on 2024-10-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_rename_product_id_order_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="order item", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(default="12 street", max_length=300),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("canceled", "canceled"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
    ]
