# Generated by Django 5.1.1 on 2024-10-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_rename_price_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(max_length=300),
        ),
    ]
