# Generated by Django 5.1.1 on 2024-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("ea", "EA"),
                    ("lb", "LB"),
                    ("box", "BOX"),
                    ("doz", "DOZ"),
                    ("kg", "KG"),
                    ("m", "M"),
                    ("g", "G"),
                    ("l", "L"),
                    ("ml", "ML"),
                    ("gal", "GAL"),
                ],
                default="ea",
                max_length=100,
            ),
        ),
    ]
