# Generated by Django 5.1.1 on 2024-10-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="date",
        ),
    ]
