# Generated by Django 5.1.1 on 2024-10-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_alter_product_catagotires"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="catagotires",
            new_name="catagoires",
        ),
    ]
