# Generated by Django 5.1.1 on 2024-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_rename_catagotires_product_catagoires"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeuser",
            name="user_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "InActive")],
                default="active",
                max_length=100,
            ),
        ),
    ]
