# Generated by Django 5.1.1 on 2024-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_rename_order_id_sale_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="name",
            field=models.CharField(default="Excersice book", max_length=100),
            preserve_default=False,
        ),
    ]
