# Generated by Django 5.1 on 2024-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_user_name_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="stuff", max_length=100),
        ),
    ]
