# Generated by Django 5.1.1 on 2024-09-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_storeuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoreUser",
        ),
    ]
