# Generated by Django 4.2.16 on 2024-09-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
