# Generated by Django 5.1.1 on 2024-10-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product_id",
            new_name="product",
        ),
    ]
