# Generated by Django 5.1.1 on 2024-10-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_order_name_order_shipping_address_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
