# Generated by Django 5.1.1 on 2024-10-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_storeuser_user_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="order_id",
            new_name="order",
        ),
    ]
