# Generated by Django 5.1.1 on 2024-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0032_alter_sale_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="order",
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_address",
            field=models.CharField(default="books", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="price",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
