# Generated by Django 5.1.1 on 2024-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0033_remove_sale_order_sale_customer_address_sale_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(auto_now_add=True)),
                ("low_stock_level_items", models.IntegerField()),
                ("sold_items_amount", models.IntegerField()),
                (
                    "sold_items_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("order_amount", models.IntegerField()),
                ("canceled_orders", models.IntegerField()),
            ],
        ),
    ]
